# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G


# Base properties
    # minecraft version
    minecraft_version=1.20.1
    # forge version, latest version can be found on https://files.minecraftforge.net/
    forge_version=47.4.0
    mapping_channel=parchment
    mapping_version=2023.09.03

# Mod Properties
    mod_version=1.6
    maven_group=net.phoenixvine.solaris
    archives_base_name=solaris
    mod_id=solaris
    mod_name=Solaris
    mod_url=
    mod_author=Phoenixvine
    mod_license=MIT

# Optional integrations
    gtceu_version=7.5.3
    kubejs_version=2001.6.5-build.16
